import { IProjects } from "config/constants/type";


const ProjectList: Array<IProjects> = [
    {
        address: '0x001',
        buyingCoin: '0x1e33833a035069f42d68D1F53b341643De1C018D',
        title: 'Ownly',
        symbol: 'OWNLY',
        image: 'ownly.png',
        desc: 'CryptoArt is still a foreign concept to many artists. The Combination of art and blockchain seems too complicated. However, we believe its rather simple.',
        longDesc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).',
        price: 1,
        progress: 100,
        totalRaise: 150,
        ownSale: 165000000.0,
        wallpaperBg: 'ownlyBg.jpg',
        status: "active",
        socMeds: ['facebook.com', 'twitter.com', 'telegram.org', 'medium.com'],
    },
    {
        address: '0x002',
        buyingCoin: '0xe09B8661D80CF24dB230A167969d18B94a5a3266',
        title: 'Lonely Token',
        symbol: 'LOWNLY',
        image: 'ownly.png',
        desc: 'CryptoArt is still a foreign concept to many artists. The Combination of art and blockchain seems too complicated. However, we believe its rather simple.',
        longDesc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).',
        price: 0.000092209,
        progress: 324575,
        totalRaise: 150,
        ownSale: 165000000.0,
        wallpaperBg: 'ownlyBg.jpg',
        status: "active",
        socMeds: ['facebook.com', 'twitter.com', 'telegram.org', 'medium.com'],
    },
    {
        address: '0x003',
        buyingCoin: '0x1e33833a035069f42d68D1F53b341643De1C018D',
        title: 'Sad Token',
        symbol: 'SADLY',
        image: 'ownly.png',
        desc: 'CryptoArt is still a foreign concept to many artists. The Combination of art and blockchain seems too complicated. However, we believe its rather simple.',
        longDesc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).',
        price: 0.0000909,
        progress: 75,
        totalRaise: 150,
        ownSale: 165000000.0,
        wallpaperBg: 'ownlyBg.jpg',
        status: "active",
        socMeds: ['facebook.com', 'twitter.com', 'telegram.org', 'medium.com'],
    },
    {
        address: '0x004',
        buyingCoin: '0x1e33833a035069f42d68D1F53b341643De1C018D',
        title: 'Ownly',
        symbol: 'OWNLY',
        image: 'ownly.png',
        desc: 'CryptoArt is still a foreign concept to many artists. The Combination of art and blockchain seems too complicated. However, we believe its rather simple.',
        longDesc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).',
        price: 0.0000909,
        progress: 75,
        totalRaise: 150,
        ownSale: 165000000.0,
        wallpaperBg: 'ownlyBg.jpg',
        status: "completed",
        socMeds: ['facebook.com', 'twitter.com', 'telegram.org', 'medium.com'],
    },
    {
        address: '0x005',
        buyingCoin: '0x1e33833a035069f42d68D1F53b341643De1C018D',
        title: 'Ownly',
        symbol: 'OWNLY',
        image: 'ownly.png',
        desc: 'CryptoArt is still a foreign concept to many artists. The Combination of art and blockchain seems too complicated. However, we believe its rather simple.',
        longDesc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).',
        price: 0.0000909,
        progress: 75,
        totalRaise: 150,
        ownSale: 165000000.0,
        wallpaperBg: 'ownlyBg.jpg',
        status: "upcoming",
        socMeds: ['facebook.com', 'twitter.com', 'telegram.org', 'medium.com'],
    },
]

export default ProjectList;